name: "🔍iz - Interactive Command Manager"
description: "A powerful TUI for managing and executing commands"

settings:
  confirm: true

# Global variables - available to all commands
variables:
  - name: "host"
    description: "Default target hostname or IP"
    default: "localhost"
    options:
      - label: "Local (localhost)"
        value: "localhost"
      - label: "Production Server"
        value: "prod.example.com"
      - label: "Development Server"
        value: "dev.example.com"
      - label: "Custom..."
        value: "custom"
  - name: "user"
    description: "Default username"
    default: "root"

commands:
  - name: "System"
    expanded: false
    children:
      - name: "List Files"
        command: "ls -la"
        description: "List all files in current directory"
        confirm: false
      
      - name: "Current Directory"
        command: "pwd"
        description: "Show current working directory"
        confirm: false
        
      - name: "Disk Usage"
        command: "df -h"
        description: "Show disk space usage"
        confirm: false

  - name: "Network"
    expanded: false
    children:
      - name: "Ping Host"
        command: "ping -c {count} {host}"
        description: "Ping a host with specified count"
        confirm: false
        variables:
          - name: "count"
            description: "Number of ping attempts"
            default: "4"
            options:
              - label: "Quick (1 ping)"
                value: "1"
              - label: "Normal (4 pings)"
                value: "4"
              - label: "Extended (10 pings)"
                value: "10"
              - label: "Custom..."
                value: "custom"
          - name: "host"
            description: "Target hostname or IP"
            default: "google.com"
            
      - name: "Check Port"
        command: "nc -zv {host} {port}"
        description: "Check if a port is open on a host"
        confirm: false
        variables:
          - name: "host"
            description: "Target hostname or IP"
            default: "localhost"
          - name: "port"
            description: "Port number to check"
            default: "80"
            options:
              - label: "HTTP (80)"
                value: "80"
              - label: "HTTPS (443)"
                value: "443"
              - label: "SSH (22)"
                value: "22"
              - label: "Custom..."
                value: "custom"

      - name: "SSH Connect"
        command: "ssh {user}@{host}"
        description: "Connect to a server via SSH (uses global variables)"
        confirm: false
        # This command uses global variables: host and user
        # No local variables defined, so it uses global defaults

      - name: "SSH with Custom Port"
        command: "ssh -p {port} {user}@{host}"
        description: "Connect via SSH with custom port"
        confirm: false
        variables:
          - name: "port"
            description: "SSH port number"
            default: "22"
        # host and user come from global variables, port is local

  - name: "Development"
    expanded: false
    children:
      - name: "Git Status"
        command: "git status"
        description: "Show git repository status"
        confirm: false
        
      - name: "Git Log"
        command: "git log --oneline -n {count}"
        description: "Show recent git commits"
        confirm: false
        variables:
          - name: "count"
            description: "Number of commits to show"
            default: "10"
            options:
              - label: "Last 5 commits"
                value: "5"
              - label: "Last 10 commits"
                value: "10"
              - label: "Last 20 commits"
                value: "20"
              - label: "Custom..."
                value: "custom"